{
 "title": "Random Gauge Dashboard",
 "templating": {
  "list": [
   {
    "name": "product",
    "label": "Product",
    "query": "label_values(random_gauge_2, product)"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "label_values(random_gauge_2, platform)"
   },
   {
    "name": "email",
    "label": "Email",
    "query": "label_values(random_gauge_2, email)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(random_gauge_2, name)"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "label_values(random_gauge_2, country)"
   }
  ]
 },
 "panels": [
  {
   "title": "Random Gauge 2 Metrics",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(random_gauge_2{product=~\".*$product\", platform=~\".*$platform\", email=~\".*$email\", name=~\".*$name\", country=~\".*$country\"})[5m]"
    }
   ]
  },
  {
   "title": "Random Gauge 1 Metrics",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(random_gauge_1{product=~\".*$product\", platform=~\".*$platform\", email=~\".*$email\", name=~\".*$name\", country=~\".*$country\"})[5m]"
    }
   ]
  },
  {
   "title": "Random Gauge 3 Metrics",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(random_gauge_3{product=~\".*$product\", platform=~\".*$platform\", email=~\".*$email\", name=~\".*$name\", country=~\".*$country\"})[5m]"
    }
   ]
  }
 ]
}
{
 "title": "Name gauge Dashboard",
 "panels": [
  {
   "title": "Name Gauge",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "name_gauge{}", "legendFormat": "{{name}}" }
   ]
  }
 ]
}